#!/bin/bash

sleep $((RANDOM%600))

if which dnf &>/dev/null; then
  dnf -q clean expire-cache
  dnf -q makecache
  dnf-automatic >/dev/null
else
  yum -e 1 -d 1 clean expire-cache
  yum -e 1 -d 1 -y update
fi

