#!/bin/bash

sleep $((RANDOM%600))

if which dnf &>/dev/null; then
  dnf -e 1 -d 1 -y clean expire-cache
  dnf -e 1 -d 1 -y upgrade
else
  yum -e 1 -d 1 clean expire-cache
  yum -e 1 -d 1 -y update
fi

